- name: Allow incoming connections on TCP port 443 (HTTPS)
  ansible.builtin.iptables:
    chain: INPUT
    action: insert
    rule_num: '6'
    ctstate: NEW
    protocol: tcp
    destination_port: '443'
    jump: ACCEPT
  notify:
    - Persist iptables

- name: Ensure PKI directory
  ansible.builtin.file:
    path: '{{ pki.directory }}'
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Ensure private key
  community.crypto.openssl_privatekey:
    type: RSA
    size: 4096
    path: '{{ pki.directory }}/{{ public_ip }}.pem'

- name: Ensure OpenSSL CSR
  community.crypto.openssl_csr:
    subject:
      O: ImgMacroBot
      CN: '{{ public_ip }}'
    privatekey_path: '{{ pki.directory }}/{{ public_ip }}.pem'
    path: '{{ pki.directory }}/{{ public_ip }}.csr'

- name: Ensure host certificate
  community.crypto.x509_certificate:
    privatekey_path: '{{ pki.directory }}/{{ public_ip }}.pem'
    csr_path: '{{ pki.directory }}/{{ public_ip }}.csr'
    provider: selfsigned
    path: '{{ pki.directory }}/{{ public_ip }}.crt'

- name: Ensure NGINX location
  ansible.builtin.template:
    src: ImgMacroBot.locations.j2
    dest: /etc/nginx/conf.d/ImgMacroBot.locations
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart NGINX

- name: Ensure NGINX config
  ansible.builtin.template:
    src: bots.conf.j2
    dest: /etc/nginx/conf.d/bots.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart NGINX
