name: Check Gradle version
on:
  - push
jobs:
  check-gradle-version:
    name: Check Gradle version
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: madhead/check-gradle-version@v1
