name: Master
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew clean assemble
      - run: zip -r templates.zip templates
      - run: zip -r fonts.zip fonts
      - run: echo "::set-output name=version::$(date +'%Y-%m-%d-%H-%M-%S')"
        id: version
      - uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version}}
          release_name: ${{ steps.version.outputs.version}}
          draft: true
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: runners/ktor/build/distributions/ImgMacroBot.tar
          asset_name: ImgMacroBot.tar
          asset_content_type: application/x-tar
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: runners/ktor/build/distributions/ImgMacroBot.zip
          asset_name: ImgMacroBot.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: templates.zip
          asset_name: templates.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: fonts.zip
          asset_name: fonts.zip
          asset_content_type: application/zip
